name: publish-crates
on:
  workflow_call:
    inputs:
      plan:
        required: false
        type: string
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true

jobs:
  crates-io:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish -p szpont --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
